### ISSUE TITLE
Broken main scene(?)

### ISSUE THREAD

**Issue by msfwaifu** [lllyasviel/YGOProUnity_V2#12]
The instruction of how it is supposed to be working are unclear and the main seems to render a broken cursor.  am I doing something wrong? 

![screenshot_22](https://user-images.githubusercontent.com/23224065/43624511-eb20b940-96b5-11e8-9bff-e4f7af64f177.png)

**Comment by mercury233** [comment]
I failed to run it in unity's window too. _Maybe it only supports exe run._

**Comment by msfwaifu** [comment]
exe run gave the same result, want to discuss more on discord about it? we might find something together. if you have some time to spare.

**Comment by mercury233** [comment]
Sorry I don't have time now.
Did you have `texture` and so on in your exe folder?

**Comment by msfwaifu** [comment]
Quick witted, will try out and see how it goes after the branch fetch & installation of unity 5.6.2f according to 44a0eaf074104d501108ee087e34c2c3fd89f9aa

**Comment by msfwaifu** [comment]
Ok. I fixed the issues, thank you @mercury233 
Added a lots of missing files to the root folder. ( textures, config, etc... ) 
![screenshot_23](https://user-images.githubusercontent.com/23224065/43625374-bdb237c2-96ba-11e8-8639-bebbe61b0851.png)

**Comment by egycno** [comment]
Hi  msfwaifu , I have the same issue , can you tell me the steps to fix the issue ?
 I copied the files for another version of ygopro2 (version without offline ai) and then moved it to the YGOProUnity_V2 folder that contains the exe file that I built in unity, and when I opened YGOProUnity_V2.exe I just showed the background without the user interface

**Comment by msfwaifu** [comment]
Hi. Sorry it  been a while since but you can try my old fork of data(s) :
https://github.com/msfwaifu/YGOProUnity_V2_Data
