### ISSUE TITLE
Broken main scene

### ISSUE THREAD

**Issue by AlperMimoglu** [lllyasviel/YGOProUnity_V2#16]
the main scene
![error](https://user-images.githubusercontent.com/55997174/73553879-9a91d400-4442-11ea-8d4c-2466fec4121e.JPG)
 is very much broken

**Comment by egycno** [comment]
I have the same issue 

https://github.com/lllyasviel/YGOProUnity_V2/issues/12

 I copied the files for another version of ygopro2 (version without offline ai) and then moved it to the YGOProUnity_V2 folder that contains the exe file that I built in unity, and when I opened YGOProUnity_V2.exe I just showed the background without the user interface

**Comment by mercury233** [comment]
would you sent the screenshot of your ygopro2 and folder structure?

**Comment by egycno** [comment]
in unity 
![in unity](https://user-images.githubusercontent.com/31624258/77648971-3fea9500-6f26-11ea-92a5-c36ca8da15e5.png)
 And the same thing when running the exe file
![the path](https://user-images.githubusercontent.com/31624258/77649388-049c9600-6f27-11ea-8e5f-4f09bcd7c4a3.png)

**Comment by mercury233** [comment]
do the exe from your downloaded ygopro2 work? can you post your built exe and data here?

**Comment by egycno** [comment]
in MyTest.exe
![2020-03-27_004447](https://user-images.githubusercontent.com/31624258/77734347-be4a4400-6fc5-11ea-8232-5b0ecc9d6657.png)
in MyTest_Data folder
![2020-03-27_004323](https://user-images.githubusercontent.com/31624258/77735007-f900ac00-6fc6-11ea-8d4b-cd725a265a0d.png)
![2020-03-27_010846](https://user-images.githubusercontent.com/31624258/77735874-8b557f80-6fc8-11ea-9a47-8d645f3df849.png)
![2020-03-27_010920](https://user-images.githubusercontent.com/31624258/77735886-927c8d80-6fc8-11ea-81dc-db559b831b56.png)
![2020-03-27_011418](https://user-images.githubusercontent.com/31624258/77735899-98726e80-6fc8-11ea-934c-dc24d6c66df9.png)
![2020-03-27_011519](https://user-images.githubusercontent.com/31624258/77735913-9d372280-6fc8-11ea-98b0-dc2f83f27b4d.png)
in MyTest.exe (ygopro2.exe)
![2020-03-27_004447](https://user-images.githubusercontent.com/31624258/77735065-15044d80-6fc7-11ea-8ed9-a69b22fe065a.png)
I can click on the window without any problems, but there is no user interface or any buttons to click on
![2020-03-27_004905](https://user-images.githubusercontent.com/31624258/77735111-2a797780-6fc7-11ea-99ed-3d9358732d6b.png)

**Comment by mercury233** [comment]
I mean, zip and send me your MyTest.exe and MyTest_Data

**Comment by egycno** [comment]
![2020-03-27_004211](https://user-images.githubusercontent.com/31624258/77761182-df765900-6ff4-11ea-83be-3c7b521dc77f.png)
There are additional files that I added from another version of  ygopro2 as msfwaifu did https://github.com/lllyasviel/YGOProUnity_V2/issues/12
The other version from which I added the files works fine but it does not contain the offline AI
![2020-03-27_063242](https://user-images.githubusercontent.com/31624258/77761199-e7ce9400-6ff4-11ea-811d-dea11ee5bfd1.png)
I tried to send the files via e-mail and by uploading them to the site in the comment box, but I have a problem with that because of the slow network I have, all I can upload now is this file
[output_log.txt](https://github.com/lllyasviel/YGOProUnity_V2/files/4393992/output_log.txt)

**Comment by mercury233** [comment]
> System.IO.FileNotFoundException: Could not find file "C:\Users\بودي\Desktop\FDM\ygopro2clone-withAI-master\ygopro2-master\config\hint.conf".
maybe you can create an empty file with this name?

**Comment by egycno** [comment]
It works!!, but when I press the AI Duel button I get this message
![2020-03-27_081430](https://user-images.githubusercontent.com/31624258/77770899-3420d080-7003-11ea-94ea-9735124c2bf7.png)
Is there a lower version available with AI Duel Offline that supports the use of new cards or at least support link cards?

**Comment by egycno** [comment]
So, is there no way to use it with any offline bot? I have a very bad internet connection and cannot use the online mode
